// Mock product data - 120+ products across multiple categories
export const PRODUCTS = [
  // Electronics - 30 products
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 6639,
    image: "/wireless-headphones.png",
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: "USB-C Cable",
    category: "Electronics",
    price: 1078,
    image: "/usb-c-cable.jpg",
    rating: 4.8,
    reviews: 456,
  },
  {
    id: 3,
    name: "Phone Stand",
    category: "Electronics",
    price: 1659,
    image: "/phone-stand.jpg",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 4,
    name: "Portable Charger",
    category: "Electronics",
    price: 2904,
    image: "/portable-charger-lifestyle.png",
    rating: 4.7,
    reviews: 567,
  },
  {
    id: 5,
    name: "Screen Protector",
    category: "Electronics",
    price: 829,
    image: "/screen-protector.png",
    rating: 4.4,
    reviews: 189,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 4149,
    image: "/bluetooth-speaker.jpg",
    rating: 4.6,
    reviews: 345,
  },
  {
    id: 7,
    name: "Webcam HD",
    category: "Electronics",
    price: 4979,
    image: "/webcam-hd.jpg",
    rating: 4.5,
    reviews: 278,
  },
  {
    id: 8,
    name: "Keyboard Mechanical",
    category: "Electronics",
    price: 7469,
    image: "/mechanical-keyboard.png",
    rating: 4.8,
    reviews: 612,
  },
  {
    id: 9,
    name: "Mouse Wireless",
    category: "Electronics",
    price: 2489,
    image: "/wireless-mouse.png",
    rating: 4.7,
    reviews: 423,
  },
  {
    id: 10,
    name: "Monitor Stand",
    category: "Electronics",
    price: 3319,
    image: "/monitor-stand.jpg",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 11,
    name: "HDMI Cable",
    category: "Electronics",
    price: 1243,
    image: "/hdmi-cable.jpg",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 12,
    name: "Power Bank 20000mAh",
    category: "Electronics",
    price: 3734,
    image: "/portable-power-bank.png",
    rating: 4.7,
    reviews: 389,
  },
  {
    id: 13,
    name: "Laptop Cooling Pad",
    category: "Electronics",
    price: 2904,
    image: "/laptop-cooling-pad.jpg",
    rating: 4.5,
    reviews: 267,
  },
  {
    id: 14,
    name: "USB Hub 7-Port",
    category: "Electronics",
    price: 2074,
    image: "/usb-hub.png",
    rating: 4.6,
    reviews: 198,
  },
  {
    id: 15,
    name: "Desk Lamp LED",
    category: "Electronics",
    price: 2489,
    image: "/desk-lamp-led.jpg",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 16,
    name: "Microphone USB",
    category: "Electronics",
    price: 5809,
    image: "/usb-microphone.jpg",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 17,
    name: "Wireless Charger",
    category: "Electronics",
    price: 2074,
    image: "/wireless-charger.png",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 18,
    name: "Phone Case",
    category: "Electronics",
    price: 1243,
    image: "/colorful-phone-case-display.png",
    rating: 4.5,
    reviews: 567,
  },
  {
    id: 19,
    name: "Screen Cleaner Kit",
    category: "Electronics",
    price: 1078,
    image: "/screen-cleaner.jpg",
    rating: 4.4,
    reviews: 123,
  },
  {
    id: 20,
    name: "Cable Organizer",
    category: "Electronics",
    price: 829,
    image: "/cable-organizer.png",
    rating: 4.5,
    reviews: 234,
  },
  {
    id: 21,
    name: "Laptop Stand",
    category: "Electronics",
    price: 3319,
    image: "/laptop-stand.png",
    rating: 4.7,
    reviews: 401,
  },
  {
    id: 22,
    name: "External SSD 1TB",
    category: "Electronics",
    price: 8299,
    image: "/external-ssd.png",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 23,
    name: "USB Flash Drive 64GB",
    category: "Electronics",
    price: 1659,
    image: "/usb-flash-drive.jpg",
    rating: 4.6,
    reviews: 278,
  },
  {
    id: 24,
    name: "Card Reader",
    category: "Electronics",
    price: 1409,
    image: "/modern-card-reader.png",
    rating: 4.5,
    reviews: 145,
  },
  {
    id: 25,
    name: "Docking Station",
    category: "Electronics",
    price: 6639,
    image: "/docking-station.jpg",
    rating: 4.7,
    reviews: 356,
  },
  {
    id: 26,
    name: "Surge Protector",
    category: "Electronics",
    price: 1908,
    image: "/surge-protector.jpg",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 27,
    name: "Extension Cord",
    category: "Electronics",
    price: 1243,
    image: "/extension-cord.jpg",
    rating: 4.5,
    reviews: 189,
  },
  {
    id: 28,
    name: "Headphone Stand",
    category: "Electronics",
    price: 1078,
    image: "/headphone-stand.jpg",
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 29,
    name: "Webcam Ring Light",
    category: "Electronics",
    price: 2904,
    image: "/ring-light.png",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 30,
    name: "Laptop Bag",
    category: "Electronics",
    price: 3734,
    image: "/laptop-bag.jpg",
    rating: 4.6,
    reviews: 412,
  },

  // Fashion - 30 products
  {
    id: 31,
    name: "Cotton T-Shirt",
    category: "Fashion",
    price: 1659,
    image: "/cotton-tshirt.png",
    rating: 4.5,
    reviews: 234,
  },
  {
    id: 32,
    name: "Jeans Blue",
    category: "Fashion",
    price: 4149,
    image: "/classic-blue-jeans.png",
    rating: 4.6,
    reviews: 456,
  },
  {
    id: 33,
    name: "Casual Sneakers",
    category: "Fashion",
    price: 5809,
    image: "/casual-sneakers.png",
    rating: 4.7,
    reviews: 567,
  },
  {
    id: 34,
    name: "Hoodie Gray",
    category: "Fashion",
    price: 3734,
    image: "/gray-hoodie.png",
    rating: 4.6,
    reviews: 345,
  },
  {
    id: 35,
    name: "Shorts Khaki",
    category: "Fashion",
    price: 2904,
    image: "/khaki-shorts.png",
    rating: 4.5,
    reviews: 278,
  },
  {
    id: 36,
    name: "Polo Shirt",
    category: "Fashion",
    price: 2489,
    image: "/classic-polo-shirt.png",
    rating: 4.6,
    reviews: 312,
  },
  {
    id: 37,
    name: "Leather Jacket",
    category: "Fashion",
    price: 10789,
    image: "/classic-leather-jacket.png",
    rating: 4.8,
    reviews: 423,
  },
  {
    id: 38,
    name: "Dress Casual",
    category: "Fashion",
    price: 4564,
    image: "/casual-dress.jpg",
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 39,
    name: "Sweater Wool",
    category: "Fashion",
    price: 4979,
    image: "/cozy-wool-sweater.png",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 40,
    name: "Socks Pack",
    category: "Fashion",
    price: 1078,
    image: "/socks-pack.jpg",
    rating: 4.5,
    reviews: 189,
  },
  {
    id: 41,
    name: "Underwear Set",
    category: "Fashion",
    price: 2074,
    image: "/underwear-set.jpg",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 42,
    name: "Scarf Wool",
    category: "Fashion",
    price: 2904,
    image: "/cozy-wool-scarf.png",
    rating: 4.7,
    reviews: 201,
  },
  {
    id: 43,
    name: "Beanie Hat",
    category: "Fashion",
    price: 1659,
    image: "/knitted-beanie.png",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 44,
    name: "Gloves Winter",
    category: "Fashion",
    price: 1908,
    image: "/winter-gloves.jpg",
    rating: 4.6,
    reviews: 198,
  },
  {
    id: 45,
    name: "Belt Leather",
    category: "Fashion",
    price: 2489,
    image: "/leather-belt.png",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 46,
    name: "Sunglasses",
    category: "Fashion",
    price: 6639,
    image: "/stylish-sunglasses.png",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 47,
    name: "Watch Casual",
    category: "Fashion",
    price: 7469,
    image: "/casual-watch.jpg",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 48,
    name: "Backpack",
    category: "Fashion",
    price: 4979,
    image: "/colorful-backpack-on-wooden-table.png",
    rating: 4.6,
    reviews: 412,
  },
  {
    id: 49,
    name: "Wallet Leather",
    category: "Fashion",
    price: 3319,
    image: "/leather-wallet.jpg",
    rating: 4.7,
    reviews: 356,
  },
  {
    id: 50,
    name: "Shoes Formal",
    category: "Fashion",
    price: 8299,
    image: "/formal-shoes.png",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 51,
    name: "Blazer",
    category: "Fashion",
    price: 9959,
    image: "/blazer.jpg",
    rating: 4.7,
    reviews: 278,
  },
  {
    id: 52,
    name: "Pants Chino",
    category: "Fashion",
    price: 4564,
    image: "/chino-pants.png",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 53,
    name: "Shirt Formal",
    category: "Fashion",
    price: 3734,
    image: "/formal-shirt.png",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 54,
    name: "Tie Silk",
    category: "Fashion",
    price: 2074,
    image: "/silk-tie.png",
    rating: 4.6,
    reviews: 145,
  },
  {
    id: 55,
    name: "Cardigan",
    category: "Fashion",
    price: 5389,
    image: "/cozy-knit-cardigan.png",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 56,
    name: "Leggings",
    category: "Fashion",
    price: 2904,
    image: "/colorful-leggings.png",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 57,
    name: "Sports Bra",
    category: "Fashion",
    price: 3734,
    image: "/diverse-athletes-sports-bras.png",
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 58,
    name: "Yoga Pants",
    category: "Fashion",
    price: 4564,
    image: "/yoga-pants.jpg",
    rating: 4.8,
    reviews: 401,
  },
  {
    id: 59,
    name: "Tank Top",
    category: "Fashion",
    price: 1243,
    image: "/simple-tank-top.png",
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 60,
    name: "Swim Trunks",
    category: "Fashion",
    price: 3319,
    image: "/swim-trunks.jpg",
    rating: 4.6,
    reviews: 212,
  },

  // Home & Kitchen - 30 products
  {
    id: 61,
    name: "Coffee Maker",
    category: "Home & Kitchen",
    price: 6639,
    image: "/modern-coffee-maker.png",
    rating: 4.7,
    reviews: 456,
  },
  {
    id: 62,
    name: "Blender",
    category: "Home & Kitchen",
    price: 4979,
    image: "/blender-3d-scene.png",
    rating: 4.6,
    reviews: 345,
  },
  {
    id: 63,
    name: "Toaster",
    category: "Home & Kitchen",
    price: 2904,
    image: "/classic-chrome-toaster.png",
    rating: 4.5,
    reviews: 267,
  },
  {
    id: 64,
    name: "Microwave",
    category: "Home & Kitchen",
    price: 8299,
    image: "/modern-microwave.png",
    rating: 4.7,
    reviews: 523,
  },
  {
    id: 65,
    name: "Dishwasher",
    category: "Home & Kitchen",
    price: 33159,
    image: "/modern-dishwasher.png",
    rating: 4.8,
    reviews: 612,
  },
  {
    id: 66,
    name: "Cutting Board",
    category: "Home & Kitchen",
    price: 1243,
    image: "/wooden-cutting-board.png",
    rating: 4.5,
    reviews: 189,
  },
  {
    id: 67,
    name: "Knife Set",
    category: "Home & Kitchen",
    price: 4149,
    image: "/knife-set.png",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 68,
    name: "Pot Set",
    category: "Home & Kitchen",
    price: 6639,
    image: "/pot-set.jpg",
    rating: 4.6,
    reviews: 412,
  },
  {
    id: 69,
    name: "Pan Non-Stick",
    category: "Home & Kitchen",
    price: 2904,
    image: "/non-stick-pan.jpg",
    rating: 4.6,
    reviews: 278,
  },
  {
    id: 70,
    name: "Baking Sheet",
    category: "Home & Kitchen",
    price: 1078,
    image: "/baking-sheet.jpg",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 71,
    name: "Measuring Cups",
    category: "Home & Kitchen",
    price: 829,
    image: "/measuring-cups.jpg",
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 72,
    name: "Mixing Bowls",
    category: "Home & Kitchen",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 234,
  },
  {
    id: 73,
    name: "Utensil Set",
    category: "Home & Kitchen",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 74,
    name: "Dish Rack",
    category: "Home & Kitchen",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 189,
  },
  {
    id: 75,
    name: "Trash Can",
    category: "Home & Kitchen",
    price: 2904,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 212,
  },
  {
    id: 76,
    name: "Vacuum Cleaner",
    category: "Home & Kitchen",
    price: 16579,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 445,
  },
  {
    id: 77,
    name: "Mop Bucket",
    category: "Home & Kitchen",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 78,
    name: "Broom Set",
    category: "Home & Kitchen",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 145,
  },
  {
    id: 79,
    name: "Sponge Pack",
    category: "Home & Kitchen",
    price: 663,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    reviews: 123,
  },
  {
    id: 80,
    name: "Dish Soap",
    category: "Home & Kitchen",
    price: 414,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 234,
  },
  {
    id: 81,
    name: "Towel Set",
    category: "Home & Kitchen",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 82,
    name: "Apron",
    category: "Home & Kitchen",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 83,
    name: "Oven Mitts",
    category: "Home & Kitchen",
    price: 1078,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 84,
    name: "Pot Holder",
    category: "Home & Kitchen",
    price: 829,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 85,
    name: "Kettle Electric",
    category: "Home & Kitchen",
    price: 2904,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 86,
    name: "Rice Cooker",
    category: "Home & Kitchen",
    price: 4149,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 87,
    name: "Slow Cooker",
    category: "Home & Kitchen",
    price: 4979,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 412,
  },
  {
    id: 88,
    name: "Air Fryer",
    category: "Home & Kitchen",
    price: 7469,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 89,
    name: "Pressure Cooker",
    category: "Home & Kitchen",
    price: 5809,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 389,
  },
  {
    id: 90,
    name: "Food Storage Containers",
    category: "Home & Kitchen",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 245,
  },

  // Books - 20 products
  {
    id: 91,
    name: "Fiction Novel",
    category: "Books",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 92,
    name: "Self-Help Book",
    category: "Books",
    price: 1409,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 345,
  },
  {
    id: 93,
    name: "Biography",
    category: "Books",
    price: 1577,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 267,
  },
  {
    id: 94,
    name: "Science Book",
    category: "Books",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 95,
    name: "History Book",
    category: "Books",
    price: 1492,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 212,
  },
  {
    id: 96,
    name: "Cookbook",
    category: "Books",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 97,
    name: "Travel Guide",
    category: "Books",
    price: 1326,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 178,
  },
  {
    id: 98,
    name: "Art Book",
    category: "Books",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 267,
  },
  {
    id: 99,
    name: "Children's Book",
    category: "Books",
    price: 1078,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 145,
  },
  {
    id: 100,
    name: "Poetry Collection",
    category: "Books",
    price: 1161,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 101,
    name: "Mystery Novel",
    category: "Books",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 223,
  },
  {
    id: 102,
    name: "Romance Novel",
    category: "Books",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 103,
    name: "Fantasy Book",
    category: "Books",
    price: 1409,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 104,
    name: "Business Book",
    category: "Books",
    price: 1577,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 105,
    name: "Programming Book",
    category: "Books",
    price: 4149,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 106,
    name: "Design Book",
    category: "Books",
    price: 2904,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 107,
    name: "Philosophy Book",
    category: "Books",
    price: 1492,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 178,
  },
  {
    id: 108,
    name: "Psychology Book",
    category: "Books",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 109,
    name: "Graphic Novel",
    category: "Books",
    price: 1825,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 110,
    name: "Comic Book",
    category: "Books",
    price: 829,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 201,
  },

  // Beauty - 20 products
  {
    id: 111,
    name: "Face Moisturizer",
    category: "Beauty",
    price: 2074,
    image: "/face-moisturizer.jpg",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 112,
    name: "Face Cleanser",
    category: "Beauty",
    price: 1659,
    image: "/face-cleanser.jpg",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 113,
    name: "Sunscreen SPF 50",
    category: "Beauty",
    price: 1908,
    image: "/sunscreen.png",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 114,
    name: "Lipstick Set",
    category: "Beauty",
    price: 2904,
    image: "/assorted-lipsticks.png",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 115,
    name: "Eye Shadow Palette",
    category: "Beauty",
    price: 3319,
    image: "/eyeshadow-palette.jpg",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 116,
    name: "Mascara Waterproof",
    category: "Beauty",
    price: 1577,
    image: "/mascara.jpg",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 117,
    name: "Foundation",
    category: "Beauty",
    price: 2489,
    image: "/building-foundation.png",
    rating: 4.7,
    reviews: 401,
  },
  {
    id: 118,
    name: "Blush Compact",
    category: "Beauty",
    price: 1243,
    image: "/blush.jpg",
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 119,
    name: "Hair Shampoo",
    category: "Beauty",
    price: 1409,
    image: "/shampoo-bottle.png",
    rating: 4.6,
    reviews: 212,
  },
  {
    id: 120,
    name: "Hair Conditioner",
    category: "Beauty",
    price: 1409,
    image: "/hair-conditioner.png",
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 121,
    name: "Hair Serum",
    category: "Beauty",
    price: 1825,
    image: "/hair-serum.jpg",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 122,
    name: "Face Mask",
    category: "Beauty",
    price: 1078,
    image: "/face-mask.jpg",
    rating: 4.5,
    reviews: 189,
  },
  {
    id: 123,
    name: "Concealer",
    category: "Beauty",
    price: 1659,
    image: "/concealer.jpg",
    rating: 4.7,
    reviews: 301,
  },
  {
    id: 124,
    name: "Bronzer Powder",
    category: "Beauty",
    price: 2074,
    image: "/bronzer.jpg",
    rating: 4.6,
    reviews: 223,
  },
  {
    id: 125,
    name: "Eyeliner Pencil",
    category: "Beauty",
    price: 1243,
    image: "/eyeliner.jpg",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 126,
    name: "Nail Polish Set",
    category: "Beauty",
    price: 2489,
    image: "/nail-polish.jpg",
    rating: 4.8,
    reviews: 389,
  },
  {
    id: 127,
    name: "Nail Art Kit",
    category: "Beauty",
    price: 2904,
    image: "/nail-art.jpg",
    rating: 4.6,
    reviews: 245,
  },
  {
    id: 128,
    name: "Perfume",
    category: "Beauty",
    price: 5389,
    image: "/elegant-perfume-display.png",
    rating: 4.8,
    reviews: 534,
  },
  {
    id: 129,
    name: "Body Lotion",
    category: "Beauty",
    price: 1908,
    image: "/body-lotion.jpg",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 130,
    name: "Lip Balm",
    category: "Beauty",
    price: 829,
    image: "/lip-balm.jpg",
    rating: 4.5,
    reviews: 134,
  },

  // Toys - 20 products
  {
    id: 131,
    name: "Action Figure",
    category: "Toys",
    price: 2904,
    image: "/action-figure.jpg",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 132,
    name: "Building Blocks Set",
    category: "Toys",
    price: 3734,
    image: "/building-blocks.jpg",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 133,
    name: "Puzzle 1000 Pieces",
    category: "Toys",
    price: 1659,
    image: "/colorful-jigsaw-puzzle.png",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 134,
    name: "Board Game",
    category: "Toys",
    price: 2074,
    image: "/board-game.jpg",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 135,
    name: "Doll Set",
    category: "Toys",
    price: 3319,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 136,
    name: "Remote Control Car",
    category: "Toys",
    price: 4979,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 137,
    name: "Drone",
    category: "Toys",
    price: 8299,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 401,
  },
  {
    id: 138,
    name: "Teddy Bear",
    category: "Toys",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 139,
    name: "Toy Robot",
    category: "Toys",
    price: 3119,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 212,
  },
  {
    id: 140,
    name: "Lego Set",
    category: "Toys",
    price: 5809,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 567,
  },
  {
    id: 141,
    name: "Yo-Yo",
    category: "Toys",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 145,
  },
  {
    id: 142,
    name: "Rubik's Cube",
    category: "Toys",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 143,
    name: "Model Car",
    category: "Toys",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 144,
    name: "Play Kitchen",
    category: "Toys",
    price: 9959,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 389,
  },
  {
    id: 145,
    name: "Toy Train Set",
    category: "Toys",
    price: 4564,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 301,
  },
  {
    id: 146,
    name: "Bicycle Toy",
    category: "Toys",
    price: 3734,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 223,
  },
  {
    id: 147,
    name: "Bubble Machine",
    category: "Toys",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 148,
    name: "Kite",
    category: "Toys",
    price: 829,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 149,
    name: "Darts Set",
    category: "Toys",
    price: 1908,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 212,
  },
  {
    id: 150,
    name: "Jigsaw Puzzle",
    category: "Toys",
    price: 1577,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 134,
  },

  // Sports - 20 products
  {
    id: 151,
    name: "Running Shoes",
    category: "Sports",
    price: 7469,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 534,
  },
  {
    id: 152,
    name: "Yoga Mat",
    category: "Sports",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 389,
  },
  {
    id: 153,
    name: "Dumbbells Set",
    category: "Sports",
    price: 6639,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 501,
  },
  {
    id: 154,
    name: "Resistance Bands",
    category: "Sports",
    price: 1908,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 155,
    name: "Basketball",
    category: "Sports",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 301,
  },
  {
    id: 156,
    name: "Football",
    category: "Sports",
    price: 1659,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 223,
  },
  {
    id: 157,
    name: "Tennis Racket",
    category: "Sports",
    price: 4979,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 345,
  },
  {
    id: 158,
    name: "Cricket Bat",
    category: "Sports",
    price: 3319,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 159,
    name: "Badminton Racket",
    category: "Sports",
    price: 2904,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 160,
    name: "Swimming Goggles",
    category: "Sports",
    price: 1243,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 161,
    name: "Bicycle",
    category: "Sports",
    price: 16579,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 612,
  },
  {
    id: 162,
    name: "Skateboard",
    category: "Sports",
    price: 4564,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 334,
  },
  {
    id: 163,
    name: "Rollerblades",
    category: "Sports",
    price: 5389,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 278,
  },
  {
    id: 164,
    name: "Jump Rope",
    category: "Sports",
    price: 1077,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 145,
  },
  {
    id: 165,
    name: "Gymnastics Ring",
    category: "Sports",
    price: 3734,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 212,
  },
  {
    id: 166,
    name: "Punching Bag",
    category: "Sports",
    price: 5809,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 423,
  },
  {
    id: 167,
    name: "Boxing Gloves",
    category: "Sports",
    price: 3119,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 168,
    name: "Treadmill",
    category: "Sports",
    price: 33159,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 567,
  },
  {
    id: 169,
    name: "Exercise Ball",
    category: "Sports",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 170,
    name: "Water Bottle",
    category: "Sports",
    price: 1908,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 334,
  },

  // Furniture - 20 products
  {
    id: 171,
    name: "Office Chair",
    category: "Furniture",
    price: 12419,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 612,
  },
  {
    id: 172,
    name: "Desk",
    category: "Furniture",
    price: 16579,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 445,
  },
  {
    id: 173,
    name: "Bookshelf",
    category: "Furniture",
    price: 8299,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 334,
  },
  {
    id: 174,
    name: "Sofa",
    category: "Furniture",
    price: 41829,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 567,
  },
  {
    id: 175,
    name: "Dining Table",
    category: "Furniture",
    price: 24839,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 401,
  },
  {
    id: 176,
    name: "Bed Frame",
    category: "Furniture",
    price: 20909,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 177,
    name: "Wardrobe",
    category: "Furniture",
    price: 24839,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 378,
  },
  {
    id: 178,
    name: "Nightstand",
    category: "Furniture",
    price: 6639,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 179,
    name: "Coffee Table",
    category: "Furniture",
    price: 9959,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 180,
    name: "Shelving Unit",
    category: "Furniture",
    price: 7469,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 181,
    name: "TV Stand",
    category: "Furniture",
    price: 8299,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 182,
    name: "Desk Lamp Stand",
    category: "Furniture",
    price: 4979,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 156,
  },
  {
    id: 183,
    name: "Filing Cabinet",
    category: "Furniture",
    price: 7469,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 184,
    name: "Gaming Chair",
    category: "Furniture",
    price: 14489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 445,
  },
  {
    id: 185,
    name: "Accent Chair",
    category: "Furniture",
    price: 9959,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 301,
  },
  {
    id: 186,
    name: "Ottoman",
    category: "Furniture",
    price: 4564,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 223,
  },
  {
    id: 187,
    name: "Mirror",
    category: "Furniture",
    price: 3319,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 145,
  },
  {
    id: 188,
    name: "Wall Shelves",
    category: "Furniture",
    price: 2489,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 212,
  },
  {
    id: 189,
    name: "Coat Rack",
    category: "Furniture",
    price: 2074,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 134,
  },
  {
    id: 190,
    name: "Shoe Rack",
    category: "Furniture",
    price: 2904,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
  },
]

export type Product = (typeof PRODUCTS)[0]
export type CartItem = Product & { quantity: number }

// Mock user data
export interface User {
  id: string
  email: string
  name: string
  password: string
}

export interface Order {
  id: string
  userId: string
  items: CartItem[]
  total: number
  date: string
  status: "pending" | "shipped" | "delivered"
}
